#!/bin/bash

# bootstrap environment
source script/bootstrap

NODE_ENV=test ./node_modules/.bin/mocha     \
  --compilers coffee:coffee-script/register \
  --reporter dot                            \
  --require coffee-script                   \
  --require test/test_helper.coffee         \
  --colors
